server:
  host: "0.0.0.0"
  port: 8086

webrtc:
  ice_servers:
    - urls: ["stun:stun.l.google.com:19302"]
    # Cloudflare TURN credentials are loaded from environment variables:
    # CF_TURN_ID and CF_TURN_KEY (set in .env file)
    # If not set, TURN will be disabled

  turn_key_id: ""
  turn_key: ""

log:
  level: "info"
