global:
  scrape_interval: 15s

scrape_configs:
  # Node Exporter (Host)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # cAdvisor (Containers)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']